// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkjO_6wDiFL8gFYdhU5ky2ULF9sgq9Enw',
    appId: '1:573359523230:web:aa1a373f29bd0ac0a2028f',
    messagingSenderId: '573359523230',
    projectId: 'elmar-learn',
    authDomain: 'elmar-learn.firebaseapp.com',
    storageBucket: 'elmar-learn.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb0DCofJrdf0WZ0V08JaeTLqUY8HGTEiM',
    appId: '1:573359523230:android:1d470d1c6b581765a2028f',
    messagingSenderId: '573359523230',
    projectId: 'elmar-learn',
    storageBucket: 'elmar-learn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvH4Dnw7nrSsFJLPJZHMX9-IAxn6SEMYE',
    appId: '1:573359523230:ios:0af963406d49538aa2028f',
    messagingSenderId: '573359523230',
    projectId: 'elmar-learn',
    storageBucket: 'elmar-learn.firebasestorage.app',
    iosClientId: '573359523230-a7qshvt67rmshvok9vpktdkspm0fu1vt.apps.googleusercontent.com',
    iosBundleId: 'com.example.lmarlearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvH4Dnw7nrSsFJLPJZHMX9-IAxn6SEMYE',
    appId: '1:573359523230:ios:0af963406d49538aa2028f',
    messagingSenderId: '573359523230',
    projectId: 'elmar-learn',
    storageBucket: 'elmar-learn.firebasestorage.app',
    iosClientId: '573359523230-a7qshvt67rmshvok9vpktdkspm0fu1vt.apps.googleusercontent.com',
    iosBundleId: 'com.example.lmarlearn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkjO_6wDiFL8gFYdhU5ky2ULF9sgq9Enw',
    appId: '1:573359523230:web:c5fd02c2a67d80eba2028f',
    messagingSenderId: '573359523230',
    projectId: 'elmar-learn',
    authDomain: 'elmar-learn.firebaseapp.com',
    storageBucket: 'elmar-learn.firebasestorage.app',
  );

}