import '../../features/courses/course.dart';

final List<Course> medicalCourses = [
  Course(
      id: '1',
      title: 'Basic Nursing',
      description: 'Learn fundamentals of nursing.',
      createdBy: 'Admin',
      imageUrl: 'img-2.jpg',
      level: 'Beginner',
      enrollmentCount: 120),
  Course(
      id: '2',
      title: 'Anatomy & Physiology',
      description: 'Deep dive into human anatomy.',
      createdBy: 'Admin',
      imageUrl: 'images.jpg',
      level: 'Intermediate',
      enrollmentCount: 95),
  Course(
      id: '3',
      title: 'Medical Ethics',
      description: 'Understand ethics in medical practice.',
      createdBy: 'Admin',
      imageUrl: 'premium.jpg',
      level: 'Advanced',
      enrollmentCount: 70),
  Course(
        id: '4',
        title: 'Pharmacology Basics',
        description: 'Introduction to pharmacology.',
        createdBy: 'Admin',
        imageUrl: 'maxresdefault.jpg',
        level: 'Beginner',
        enrollmentCount: 85),
    Course(
        id: '5',
        title: 'Patient Care Techniques',
        description: 'Best practices for patient care.',
        createdBy: 'Admin',
        imageUrl: 'maxresdefault.jpg',
        level: 'Intermediate',
        enrollmentCount: 110),
    Course(
        id: '6',
        title: 'Infection Control',
        description: 'Methods to prevent infections in healthcare.',
        createdBy: 'Admin',
        imageUrl: '7830105-612x612.jpg',
        level: 'Advanced',
        enrollmentCount: 60),
    Course(
        id: '7',
        title: 'Emergency Nursing',
        description: 'Handling emergencies in nursing.',
        createdBy: 'Admin',
        imageUrl: 'img-2.jpg',
        level: 'Advanced',
        enrollmentCount: 45),
    Course(
        id: '8',
        title: 'Pediatric Nursing',
        description: 'Caring for children in medical settings.',
        createdBy: 'Admin',
        imageUrl: 'images.jpg',
        level: 'Intermediate',
        enrollmentCount: 75),
    Course(
        id: '9',
        title: 'Geriatric Care',
        description: 'Specialized care for the elderly.',
        createdBy: 'Admin',
        imageUrl: 'premium.jpg',
        level: 'Beginner',
        enrollmentCount: 50),
    Course(
        id: '10',
        title: 'Mental Health Nursing',
        description: 'Supporting mental health in nursing practice.',
        createdBy: 'Admin',
        imageUrl: 'maxresdefault.jpg',
        level: 'Advanced',
        enrollmentCount: 40), 
    Course(
        id: '11',
        title: 'Surgical Nursing',
        description: 'Nursing care in surgical settings.',
        createdBy: 'Admin',
        imageUrl: '7830105-612x612.jpg',
        level: 'Intermediate',
        enrollmentCount: 55),
    Course(
        id: '12',
        title: 'Community Health Nursing',
        description: 'Promoting health in communities.',
        createdBy: 'Admin',
        imageUrl: 'img-2.jpg',
        level: 'Beginner',
        enrollmentCount: 65), 
    Course(
        id: '13',
        title: 'Critical Care Nursing',
        description: 'Caring for critically ill patients.',
        createdBy: 'Admin',
        imageUrl: 'images.jpg',
        level: 'Advanced',
        enrollmentCount: 30),
    Course(
        id: '14',
        title: 'Obstetric Nursing',
        description: 'Nursing care for pregnant women.',
        createdBy: 'Admin',
        imageUrl: 'premium.jpg',
        level: 'Intermediate',
        enrollmentCount: 45),
    Course(
        id: '15',
        title: 'Health Assessment',
        description: 'Techniques for comprehensive health assessments.',
        createdBy: 'Admin',
        imageUrl: 'maxresdefault.jpg',
        level: 'Beginner',
        enrollmentCount: 90),
    Course(
        id: '16',
        title: 'Wound Care Management',
        description: 'Effective wound care techniques.',
        createdBy: 'Admin',
        imageUrl: '7830105-612x612.jpg',
        level: 'Intermediate',
        enrollmentCount: 70),    
];
